import { defineArrayMember, defineField, defineType } from "sanity";

export const raceSettings = defineType({
  name: "raceSettings",
  title: "The Race",
  type: "document",
  groups: [
    { name: "landing", title: "Leaderboard", default: true },
    { name: "table", title: "Leaderboard Labels" },
    { name: "model", title: "Model Pages" },
    { name: "methodology", title: "Methodology" },
    { name: "structured", title: "Structured Data" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({ name: "eyebrow", title: "Status eyebrow", type: "string", group: "landing", validation: (Rule) => Rule.required() }),
    defineField({ name: "headingPrefix", title: "Heading before emphasis", type: "string", group: "landing", validation: (Rule) => Rule.required() }),
    defineField({ name: "headingEmphasis", title: "Italic emphasis", type: "string", group: "landing", validation: (Rule) => Rule.required() }),
    defineField({ name: "headingSuffix", title: "Heading after emphasis", type: "string", group: "landing", validation: (Rule) => Rule.required() }),
    defineField({ name: "definitionTemplate", title: "Dynamic introduction", type: "text", rows: 6, group: "landing", description: "Available tokens: {date}, {model}, {organization}, {country}, {usCount}, {usWord}, {cnCount}, {cnWord}.", validation: (Rule) => Rule.required() }),
    defineField({ name: "lastUpdatedLabel", title: "Last updated label", type: "string", group: "landing", validation: (Rule) => Rule.required() }),
    defineField({ name: "themeLabel", title: "Theme label", type: "string", group: "landing", validation: (Rule) => Rule.required() }),
    defineField({ name: "methodologyAction", title: "Methodology action", type: "callToAction", group: "landing", validation: (Rule) => Rule.required() }),
    defineField({ name: "dateLocale", title: "Date locale", type: "string", group: "landing", description: "BCP 47 locale used for displayed dates, for example en-US.", initialValue: "en-US", validation: (Rule) => Rule.required() }),

    defineField({ name: "leaderboardAriaLabel", title: "Leaderboard accessibility label", type: "string", group: "table", validation: (Rule) => Rule.required() }),
    defineField({ name: "tableCaption", title: "Table caption", type: "string", group: "table", validation: (Rule) => Rule.required() }),
    defineField({ name: "rankColumnLabel", title: "Rank column", type: "string", group: "table", validation: (Rule) => Rule.required() }),
    defineField({ name: "modelColumnLabel", title: "Model column", type: "string", group: "table", validation: (Rule) => Rule.required() }),
    defineField({ name: "organizationColumnLabel", title: "Organization column", type: "string", group: "table", validation: (Rule) => Rule.required() }),
    defineField({ name: "countryColumnLabel", title: "Country column", type: "string", group: "table", validation: (Rule) => Rule.required() }),
    defineField({ name: "typeColumnLabel", title: "Type column", type: "string", group: "table", validation: (Rule) => Rule.required() }),
    defineField({ name: "releasedColumnLabel", title: "Released column", type: "string", group: "table", validation: (Rule) => Rule.required() }),
    defineField({ name: "benchmarkColumnLabel", title: "Benchmark column", type: "string", group: "table", validation: (Rule) => Rule.required() }),
    defineField({ name: "newRankLabel", title: "New-rank label", type: "string", group: "table", validation: (Rule) => Rule.required() }),
    defineField({ name: "footballComingSoonTemplate", title: "Football-theme placeholder", type: "string", group: "table", description: "Available token: {count}.", validation: (Rule) => Rule.required() }),
    defineField({ name: "logoAltTemplate", title: "Organization logo alt-text template", type: "string", group: "table", description: "Available token: {organization}.", validation: (Rule) => Rule.required() }),

    defineField({ name: "modelNotFoundTitle", title: "Missing-model metadata title", type: "string", group: "model", validation: (Rule) => Rule.required() }),
    defineField({ name: "modelBackAction", title: "Back action", type: "callToAction", group: "model", validation: (Rule) => Rule.required() }),
    defineField({ name: "modelIntroductionTemplate", title: "Model introduction", type: "text", rows: 5, group: "model", description: "Available tokens: {model}, {type}, {organization}, {country}, {releaseDate}, {rank}.", validation: (Rule) => Rule.required() }),
    defineField({ name: "dataStatusLabel", title: "Data-status label", type: "string", group: "model", validation: (Rule) => Rule.required() }),
    defineField({ name: "unverifiedStatusLabel", title: "Unverified status", type: "string", group: "model", validation: (Rule) => Rule.required() }),
    defineField({ name: "reviewStatusLabel", title: "Under-review status", type: "string", group: "model", validation: (Rule) => Rule.required() }),
    defineField({ name: "verifiedStatusLabel", title: "Verified status", type: "string", group: "model", validation: (Rule) => Rule.required() }),
    defineField({ name: "organizationLabel", title: "Organization label", type: "string", group: "model", validation: (Rule) => Rule.required() }),
    defineField({ name: "countryLabel", title: "Country-of-origin label", type: "string", group: "model", validation: (Rule) => Rule.required() }),
    defineField({ name: "modelTypeLabel", title: "Model-type label", type: "string", group: "model", validation: (Rule) => Rule.required() }),
    defineField({ name: "releaseDateLabel", title: "Release-date label", type: "string", group: "model", validation: (Rule) => Rule.required() }),
    defineField({ name: "currentRankLabel", title: "Current-rank label", type: "string", group: "model", validation: (Rule) => Rule.required() }),
    defineField({ name: "benchmarkScoreLabel", title: "Benchmark-score label", type: "string", group: "model", validation: (Rule) => Rule.required() }),
    defineField({ name: "benchmarkUnsourcedLabel", title: "Missing benchmark label", type: "string", group: "model", validation: (Rule) => Rule.required() }),
    defineField({ name: "marketStatusLabel", title: "Market-status label", type: "string", group: "model", validation: (Rule) => Rule.required() }),
    defineField({ name: "publicMarketTemplate", title: "Public-market value", type: "string", group: "model", description: "Available tokens: {exchange}, {ticker}.", validation: (Rule) => Rule.required() }),
    defineField({ name: "privateMarketFallback", title: "Private-market fallback", type: "string", group: "model", validation: (Rule) => Rule.required() }),
    defineField({ name: "sourcesHeading", title: "Sources heading", type: "string", group: "model", validation: (Rule) => Rule.required() }),
    defineField({ name: "sourceLinkLabel", title: "Inline source-link label", type: "string", group: "model", validation: (Rule) => Rule.required() }),
    defineField({ name: "modelMethodologyLinkLabel", title: "Methodology link label", type: "string", group: "model", validation: (Rule) => Rule.required() }),
    defineField({ name: "modelSeoTitleTemplate", title: "Model SEO title", type: "string", group: "model", description: "Available tokens: {model}.", validation: (Rule) => Rule.required() }),
    defineField({ name: "modelSeoDescriptionTemplate", title: "Model SEO description", type: "text", rows: 4, group: "model", description: "Available tokens: {model}, {organization}, {country}, {releaseDate}.", validation: (Rule) => Rule.required() }),

    defineField({ name: "methodologyBackAction", title: "Back action", type: "callToAction", group: "methodology", validation: (Rule) => Rule.required() }),
    defineField({ name: "methodologyHeading", title: "Heading", type: "string", group: "methodology", validation: (Rule) => Rule.required() }),
    defineField({
      name: "methodologyNotice",
      title: "Status notice",
      type: "object",
      group: "methodology",
      fields: [
        defineField({ name: "label", title: "Label", type: "string", validation: (Rule) => Rule.required() }),
        defineField({ name: "body", title: "Body", type: "text", rows: 5, validation: (Rule) => Rule.required() }),
        defineField({ name: "tone", title: "Tone", type: "string", options: { list: ["warning", "information"], layout: "radio" }, initialValue: "warning", validation: (Rule) => Rule.required() }),
      ],
      validation: (Rule) => Rule.required(),
    }),
    defineField({ name: "methodologyNeedsHeading", title: "Requirements heading", type: "string", group: "methodology", validation: (Rule) => Rule.required() }),
    defineField({ name: "methodologyNeeds", title: "Requirements", type: "array", group: "methodology", of: [defineArrayMember({ type: "text", rows: 3 })], validation: (Rule) => Rule.required().min(1) }),
    defineField({ name: "methodologySourceNote", title: "Source note", type: "string", group: "methodology", validation: (Rule) => Rule.required() }),
    defineField({ name: "methodologySeo", title: "Methodology SEO", type: "seo", group: "seo", validation: (Rule) => Rule.required() }),

    defineField({ name: "itemListName", title: "ItemList name", type: "string", group: "structured", validation: (Rule) => Rule.required() }),
    defineField({ name: "itemListDescription", title: "ItemList description", type: "text", rows: 3, group: "structured", validation: (Rule) => Rule.required() }),
    defineField({ name: "highestModelQuestion", title: "Highest-model FAQ question", type: "string", group: "structured", validation: (Rule) => Rule.required() }),
    defineField({ name: "highestModelAnswerTemplate", title: "Highest-model FAQ answer", type: "string", group: "structured", description: "Available tokens: {model}, {organization}.", validation: (Rule) => Rule.required() }),
    defineField({ name: "refreshQuestion", title: "Refresh FAQ question", type: "string", group: "structured", validation: (Rule) => Rule.required() }),
    defineField({ name: "refreshAnswer", title: "Refresh FAQ answer", type: "text", rows: 3, group: "structured", validation: (Rule) => Rule.required() }),
    defineField({ name: "applicationCategory", title: "Model application category", type: "string", group: "structured", validation: (Rule) => Rule.required() }),
    defineField({ name: "seo", title: "Leaderboard SEO", type: "seo", group: "seo", validation: (Rule) => Rule.required() }),
  ],
  preview: { prepare: () => ({ title: "The Race", subtitle: "Leaderboard, model pages and methodology" }) },
});
