import type { Article } from "@/lib/types";

export const mockArticles: Article[] = [
  {
    _id: "mock-1",
    title: "The Autonomous Agent Is No Longer a Prototype. It Is Your Next Employee.",
    slug: { current: "autonomous-agent-next-employee" },
    tagType: "deep-dive",
    industryTag: "cross-industry",
    deck: "Enterprise AI crossed a threshold in 2025. Autonomous agents are no longer demos at conferences — they are signing contracts, triaging records, and writing code that ships to production.",
    author: "The Hivig Editorial Team",
    readTimeMinutes: 14,
    publishedAt: "2026-03-01T09:00:00Z",
    platformTags: ["AWS Bedrock", "Salesforce Agentforce"],
    featured: true,
  },
  {
    _id: "mock-2",
    title: "Build a Multi-Step Reasoning Agent on AWS Bedrock in 45 Minutes",
    slug: { current: "bedrock-agent-45-minutes" },
    tagType: "how-to",
    industryTag: "tech-saas",
    deck: "From IAM roles to Knowledge Base integration — a precise, production-grade walkthrough with no hand-waving.",
    author: "The Hivig Editorial Team",
    readTimeMinutes: 12,
    publishedAt: "2026-02-20T09:00:00Z",
    platformTags: ["AWS Bedrock"],
    featured: true,
  },
  {
    _id: "mock-3",
    title: "How Can AI Reduce SDR Prospecting Time for a B2B SaaS Sales Team?",
    slug: { current: "ai-reduce-sdr-prospecting-time" },
    tagType: "how-to",
    industryTag: "tech-saas",
    deck: "A workflow-level breakdown of where agentic AI genuinely saves SDR hours, and where it still requires human judgment.",
    author: "The Hivig Editorial Team",
    readTimeMinutes: 9,
    publishedAt: "2026-02-15T09:00:00Z",
    platformTags: ["Salesforce Agentforce", "AWS Bedrock"],
    featured: true,
  },
  {
    _id: "mock-4",
    title: "Which AI Models Are Best Suited for Enterprise Financial Research Workflows?",
    slug: { current: "ai-models-financial-research" },
    tagType: "verify",
    industryTag: "financial-services",
    deck: "We tested five frontier models against real financial research tasks. The results were not what the marketing pages suggest.",
    author: "The Hivig Editorial Team",
    readTimeMinutes: 11,
    publishedAt: "2026-02-10T09:00:00Z",
    platformTags: ["Anthropic Claude", "Google Gemini"],
    featured: true,
  },
  {
    _id: "mock-5",
    title: "The MCP Protocol Is the Most Important Standard Nobody Is Talking About",
    slug: { current: "mcp-protocol-standard" },
    tagType: "opinion",
    industryTag: "cross-industry",
    deck: "Anthropic's Model Context Protocol is quietly becoming the connective tissue of the agentic internet.",
    author: "The Hivig Editorial Team",
    readTimeMinutes: 8,
    publishedAt: "2026-02-05T09:00:00Z",
    platformTags: ["Anthropic Claude", "Open Source"],
  },
];
