import { defineArrayMember, defineField, defineType } from "sanity";

export const article = defineType({
  name: "article",
  title: "Article",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "meta", title: "Metadata & SEO" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      group: "content",
      validation: (Rule) => Rule.required().max(120),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "content",
      options: { source: "title", maxLength: 96 },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "tagType",
      title: "Article Type",
      type: "reference",
      group: "content",
      to: [{ type: "articleType" }],
      options: { filter: "active != false" },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "industryTag",
      title: "Industry",
      type: "reference",
      group: "content",
      to: [{ type: "industry" }],
      options: { filter: "active != false" },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "deck",
      title: "Deck (1-2 sentence summary)",
      type: "text",
      group: "content",
      rows: 3,
      validation: (Rule) => Rule.required().max(280),
    }),
    defineField({
      name: "heroMedia",
      title: "Hero image",
      type: "imageWithAlt",
      group: "content",
    }),
    defineField({
      name: "heroImage",
      title: "Legacy hero image",
      type: "image",
      group: "content",
      options: { hotspot: true },
      hidden: true,
      deprecated: { reason: "Use Hero image, which requires accessible alternative text." },
    }),
    defineField({
      name: "body",
      title: "Body",
      type: "array",
      group: "content",
      of: [
        {
          type: "block",
          styles: [
            { title: "Normal", value: "normal" },
            { title: "H2", value: "h2" },
            { title: "H3", value: "h3" },
            { title: "Quote", value: "blockquote" },
          ],
          marks: {
            annotations: [
              {
                name: "link",
                title: "Link",
                type: "object",
                fields: [
                  defineField({
                    name: "href",
                    title: "URL",
                    type: "url",
                    validation: (Rule) => Rule.required().uri({ scheme: ["http", "https", "mailto"] }),
                  }),
                ],
              },
            ],
          },
        },
        {
          type: "image",
          options: { hotspot: true },
          fields: [
            defineField({
              name: "alt",
              title: "Alternative text",
              type: "string",
              validation: (Rule) => Rule.required(),
            }),
            defineField({ name: "caption", title: "Caption", type: "string" }),
            defineField({ name: "credit", title: "Credit", type: "string" }),
          ],
        },
        {
          type: "code",
          title: "Code Block",
        },
        { type: "stlTableBlock" },
      ],
    }),
    defineField({
      name: "author",
      title: "Author",
      type: "reference",
      group: "content",
      to: [{ type: "author" }],
      options: { filter: "active != false" },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "readTimeMinutes",
      title: "Estimated Read Time (minutes)",
      type: "number",
      group: "content",
      validation: (Rule) => Rule.required().min(1).max(60),
    }),
    defineField({
      name: "publishedAt",
      title: "Published Date",
      type: "datetime",
      group: "content",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "platformTags",
      title: "Related Platforms",
      type: "array",
      group: "content",
      of: [defineArrayMember({ type: "reference", to: [{ type: "platform" }] })],
      validation: (Rule) => Rule.unique(),
    }),
    defineField({
      name: "featured",
      title: "Feature on Homepage",
      type: "boolean",
      group: "content",
      initialValue: false,
    }),
    defineField({ name: "featurePriority", title: "Homepage feature priority", type: "number", group: "content", hidden: ({ parent }) => !parent?.featured, validation: (Rule) => Rule.integer().min(0) }),
    defineField({ name: "reviewedAt", title: "Last reviewed", type: "datetime", group: "meta" }),
    defineField({ name: "sources", title: "Sources", type: "array", group: "meta", of: [defineArrayMember({ type: "reference", to: [{ type: "sourceCitation" }] })], validation: (Rule) => Rule.unique() }),
    defineField({ name: "relatedArticles", title: "Related articles", type: "array", group: "meta", of: [defineArrayMember({ type: "reference", to: [{ type: "article" }] })], validation: (Rule) => Rule.unique() }),
    defineField({ name: "seo", title: "SEO and social sharing", type: "seo", group: "meta" }),
    defineField({
      name: "metaTitle",
      title: "Legacy meta title",
      type: "string",
      group: "meta",
      hidden: true,
      deprecated: { reason: "Use the SEO and social sharing field." },
      validation: (Rule) => Rule.max(70),
    }),
    defineField({
      name: "metaDescription",
      title: "Legacy meta description",
      type: "text",
      group: "meta",
      hidden: true,
      deprecated: { reason: "Use the SEO and social sharing field." },
      rows: 2,
      validation: (Rule) => Rule.max(160),
    }),
  ],
  preview: {
    select: { title: "title", type: "tagType.name", author: "author.name", media: "heroMedia.image" },
    prepare: ({ title, type, author, media }) => ({ title, subtitle: [type, author].filter(Boolean).join(" · "), media }),
  },
});
